on: [push]

jobs:
  terrascan_terraform_job:
    runs-on: ubuntu-latest
    name: tfsec
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        gif: true